### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hellowtf01** [DamianeK02/DiscordAccountTokenGenerator#12]
Just open CMD - started and don't complete all task need to press manualy for date of birth and verify butoon and then the account get lock for sms verification.If you can implement 5sim.net for verify and 2captcha.com and fixx the problem with date of birth to be completele automacly you are the best !

**Comment by daleputo** [comment]
yessss please, do what the guy above me says!!! pretty pls

**Comment by DamianeK02** [comment]
check repo it's up to date
