### ISSUE TITLE
Getting a Bluetooth error when running 

### ISSUE THREAD

**Issue by logandiros** [DamianeK02/DiscordAccountTokenGenerator#14]
for some reason it says there is an issue with bluetooth and then it wont continue creating the accounts. need help please

**Comment by JaxonYon** [comment]
Same

**Comment by DumbDannyLol** [comment]
I have updated the repository, just head over to Pull Requests and click on mine. I am waiting for the owner to merge my request, then the process will be easier.

**Comment by DamianeK02** [comment]
yeah sorry, now it's up to date

**Comment by DamianeK02** [comment]
yeah sorry, now it's up to date
