### ISSUE TITLE
isnt working

### ISSUE THREAD

**Issue by finns-123** [DamianeK02/DiscordAccountTokenGenerator#15]
it dosent fill out the date of birth and in the cmd comes up with this error "C:\Users\monst\Downloads\DiscordAccountTokenGenerator-main\DiscordAccountTokenGenerator-main>[19892:18944:0717/132702.516:ERROR:device_event_log_impl.cc(214)] [13:27:02.516] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)"

**Comment by DumbDannyLol** [comment]
If you head over to Pull Requests, and you find mine, I have an updated version that works. I am just waiting for the owner of this repository to merge my request, then the process will be easier.

**Comment by DamianeK02** [comment]
yeah sorry, now it's up to date
