### ISSUE TITLE
Solver Extension Contains a Potentially Malicious API Endpoint

### ISSUE THREAD

**Issue by AngeloD2022** [DamianeK02/DiscordAccountTokenGenerator#22]
In the extension, there is a file named `background.js`. 

`background.js` contains the below function...

<img width="1019" alt="CleanShot 2022-12-02 at 22 30 14@2x" src="https://user-images.githubusercontent.com/43831545/205420695-df3f0d43-6389-4e99-9f56-9852f80cb66b.png">

`https://gtechmonitor.com/a` contains obfuscated JSON data...

![CleanShot 2022-12-02 at 22 33 23@2x](https://user-images.githubusercontent.com/43831545/205420789-bb52b4ac-2138-4212-9260-d1ce209e1ba5.png)

Deobfuscating this results in...
<img width="846" alt="CleanShot 2022-12-02 at 22 49 04@2x" src="https://user-images.githubusercontent.com/43831545/205421225-29095ae8-eb07-48c3-98ee-55838ae9363a.png">

This data appears to be a list of patterns used to redirect to a page: `https://gtechmonitor.com/a?__u=\1` as indicated by `t.s`
<img width="815" alt="CleanShot 2022-12-02 at 22 50 30@2x" src="https://user-images.githubusercontent.com/43831545/205421281-ce1a1b18-483e-40fd-87bf-1c155f345b03.png">

**Comment by AngeloD2022** [comment]
[solver.zip](https://github.com/DamianeK02/DiscordAccountTokenGenerator/files/10145572/solver.zip)
Attaching the solver source for research purposes.

**Comment by DamianeK02** [comment]
U mean solver.crx from chrome?

**Comment by AngeloD2022** [comment]
> U mean solver.crx from chrome?

solver.crx from Google Drive.

**Comment by DamianeK02** [comment]
Okay i removed this.
Thank you for info

**Comment by DamianeK02** [comment]
**sorry but this project is no longer supported**
